name: CD
on:
 push:
  tags: 'v*'
env:
 BUILD_TYPE: Release
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Generate Package
    run: |
     mkdir -p build
     cd build
     version="${GITHUB_REF##*/*/}"
     echo ::set-output name=version::$version
     cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCPACK_PACKAGE_VERSION:STRING=$version -DCPACK_SYSTEM_NAME:STRING=linux-Release ..
     cmake --build . --config ${{env.BUILD_TYPE}}
     cmake --build . --target package
  - name: Upload
    uses: softprops/action-gh-release@v1
    with:
     files: "build/*.tar.gz"
    env:
     GITHUB_TOKEN: ${{secrets.TOKEN}}