name: CI
on:
 push: 
  branches: [ "main" ]
env:
 BUILD_TYPE: Release
jobs: 
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: Configure CMake
     run: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
      cmake --build . --config ${{env.BUILD_TYPE}}
      ctest -C ${{env.BUILD_TYPE}}
      
 semantic-release:
  runs-on: ubuntu-latest
  needs: [build]
  steps:
  - uses: actions/checkout@v4
    with:
     token: ${{ secrets.TOKEN }}
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v4
    with:
     semantic_version: 15.13.28
     branch: main
    env:
     GITHUB_TOKEN: ${{ secrets.TOKEN }}